# Generated by Django 4.1.5 on 2023-01-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, null=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_type', models.SmallIntegerField(null=True)),
                ('trainer_group', models.IntegerField(default=0)),
                ('user_height', models.FloatField(null=True)),
                ('user_weight', models.FloatField(null=True)),
                ('user_status', models.SmallIntegerField(default=1)),
                ('user_view', models.SmallIntegerField(default=1)),
                ('user_gender', models.SmallIntegerField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
