# Generated by Django 4.1.3 on 2022-11-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trainer_group',
            field=models.IntegerField(default=0),
        ),
    ]
