# Generated by Django 4.1.3 on 2022-11-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_trainer_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_view',
            field=models.SmallIntegerField(default=1),
        ),
    ]
