# Generated by Django 4.1.5 on 2023-01-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.IntegerField(null=True),
        ),
    ]
