# Generated by Django 4.1.3 on 2022-11-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_weight',
            field=models.FloatField(null=True),
        ),
    ]
