# Generated by Django 4.1.3 on 2023-01-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypeboy', '0002_lesson_start_date_lesson_total_completion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='view_yn',
            field=models.IntegerField(default=0),
        ),
    ]
