# Generated by Django 4.1.3 on 2023-01-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypeboy', '0003_lesson_view_yn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='completion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='set',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='view_yn',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='weight',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
